// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rysxmxqranwzmdlxljiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5c3hteHFyYW53em1kbHhsaml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODYxMDUsImV4cCI6MjA2NDc2MjEwNX0.7W12_-TBbJHVvXmMDH6Nf9er1Whs-jGwf-807SI59pA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);